### ISSUE TITLE
failed to register layer: disk quota exceeded docker

### ISSUE THREAD

**Issue by capriciousduck** [hectorm/docker-xubuntu#9] opened 2021-06-14 06:39 UTC
I am getting the following error even if I have 84Gb available.

`failed to register layer: disk quota exceeded docker`

What do I do now?

**Comment by hectorm** [comment] 2021-06-14 17:20
I think this has nothing to do with this image, there is something wrong with your system.

Tell me more details about your environment (OS, Docker version, command you are running, etc).

**Comment by capriciousduck** [comment] 2021-06-15 04:46
Mine is Ubuntu 20.04 and the docker version is 20.10.2.

When I pull the image I get the failed to register error.

`docker pull hectormolinero/xubuntu:latest`

**Comment by hectorm** [comment] 2021-06-29 18:49
I'm sorry but I'm going to close this issue because this problem has nothing to do with this particular image and I don't know the cause of your error.

**Closed as completed by hectorm** 2021-06-29 18:49 UTC
