### ISSUE TITLE
adding custom device "/dev/dri": no such file or directory.

### ISSUE THREAD

**Issue by andrewufrank** [hectorm/docker-xubuntu#2] opened 2020-08-26 11:20 UTC
I tried to use your docker image to add xfce to a raspberry4 running the 64bit ubuntu 20.10.  When run it with your instruction i get when it tries to start the container: 

    response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory.

I have no idea what device `/dev/dri` could be and I do not see it in your Dockerfile. 
I need only a basic `xfce4` installation (preferably on debian - as you provide). What pieces of the Dockerfile can I leave out and add later as additional images (like you did with `steam`)?

muchas gracias por tus resultados!
andres

docker run \
  --name xubuntu \
  --detach \
  --shm-size 2g \
  --publish 3322:3322/tcp \
  --publish 3389:3389/tcp \
  --device /dev/dri:/dev/dri \
  hectormolinero/xubuntu:latest

**Comment by hectorm** [comment] 2020-08-26 12:57
> I have no idea what device /dev/dri could be and I do not see it in your Dockerfile.

It's possible that your system doesn't have the vc4 module enabled. I've a Raspberry Pi 4 with Raspbian and it works fine, I don't know if it's different on Ubuntu 20.04. I'll investigate it when I've some time.

```
pi@raspberry:~ $ ls -la /dev/dri/
total 0
drwxr-xr-x  3 root root        120 Aug 25 05:30 .
drwxr-xr-x 18 root root       3760 Aug 25 05:30 ..
drwxr-xr-x  2 root root        100 Aug 25 05:30 by-path
crw-rw----  1 root video  226,   0 Aug 25 05:30 card0
crw-rw----  1 root video  226,   1 Aug 25 05:30 card1
crw-rw----  1 root render 226, 128 Aug 25 05:30 renderD128
pi@raspberry:~ $ lsmod | grep vc4
vc4                   237568  0
cec                    49152  1 vc4
drm_kms_helper        184320  2 vc4
drm                   458752  5 v3d,vc4,gpu_sched,drm_kms_helper
snd_soc_core          200704  1 vc4
snd_pcm                98304  3 vc4,snd_pcm_dmaengine,snd_soc_core
pi@raspberry:~ $ docker run --name xubuntu --detach --shm-size 2g --publish 3322:3322/tcp --publish 3389:3389/tcp --device /dev/dri:/dev/dri hectormolinero/xubuntu:latest
pi@raspberry:~ $ docker logs xubuntu
Generating RSA private key, 2048 bit long modulus (2 primes)
..................................................................................................+++++
.................+++++
e is 65537 (0x010001)
Signature ok
subject=CN = 0d0f31b099f8
Getting Private key
[20200826-12:48:45] [INFO ] starting xrdp-sesman with pid 52
[20200826-12:48:45] [INFO ] listening to port 3350 on 127.0.0.1
[20200826-12:48:45] [INFO ] starting xrdp with pid 53
[20200826-12:48:45] [INFO ] address [0.0.0.0] port [3389] mode 1
[20200826-12:48:45] [INFO ] listening to port 3389 on 0.0.0.0
[20200826-12:48:45] [INFO ] xrdp_listen_pp done
```

> I need only a basic xfce4 installation (preferably on debian - as you provide). What pieces of the Dockerfile can I leave out and add later as additional images (like you did with steam)?

You can start by forking the project and removing all the packages you are not interested in.
https://github.com/hectorm/docker-xubuntu/blob/v51/Dockerfile.m4#L224-L368

**Comment by hectorm** [comment] 2020-08-27 12:24
I tested a Raspberry Pi 4 with Ubuntu 20.04 and `/dev/dri` exists, I think there is something wrong with your system.

Anyway you can omit the `--device /dev/dri:/dev/dri` option completely if you don't plan to use the GPU.

I'm going to close this issue since I think there is no problem with this image. But I'm willing to reopen it if there is another related issue that I can reproduce.

**Closed as completed by hectorm** 2020-08-27 12:24 UTC

**Comment by andrewufrank** [comment] 2020-09-10 09:19
Thank you - I will try without the `dri` line!

**Comment by Stardust-minus** [comment] 2022-09-03 12:28
> I tested a Raspberry Pi 4 with Ubuntu 20.04 and `/dev/dri` exists, I think there is something wrong with your system.
> 
> Anyway you can omit the `--device /dev/dri:/dev/dri` option completely if you don't plan to use the GPU.
> 
> I'm going to close this issue since I think there is no problem with this image. But I'm willing to reopen it if there is another related issue that I can reproduce.

Is it possible to use GPU without  --device /dev/dri:/dev/dri option?
My GPU is V100-SXM2,and for some reason I can't use such option.

**Comment by hectorm** [comment] 2022-09-08 17:08
It is necessary to specify the `/dev/dri` device to use the GPU and also to have the GPU drivers installed on the host in the same version included in the image, v515 for nvidia right now. In case you are using Linux try to run the image with the `run.sh` script included in the project and tell me if the GPU is detected.
